---
name: Filiibot
version: dev
slug: filiibot
description: A Filiibot add-on for Home Assistant
url: https://github.com/filii-lamberti/addon-filiibot
init: false
arch:
  - aarch64
  - amd64
  - armhf
  - armv7
  - i386
hassio_api: true
homeassistant_api: true
options:
  token:
  prefix: +
schema:
  logging: bool?
  debugging: bool?
  token: match(^[A-Za-z0-9\\.]+$)
  prefix: match(^.$)
image: ghcr.io/filii-lamberti/filiibot/{arch}