version: 2
updates:
- package-ecosystem: github-actions
  directory: "/"
  schedule:
    interval: daily
- package-ecosystem: docker
  directory: "/filiibot"
  schedule:
    interval: daily
- package-ecosystem: npm
  directory: "/filiibot/rootfs/opt/filiibot"
  schedule:
    interval: daily
