name: Continuous deployment

on:
  push:
    # Sequence of patterns matched against refs/tags
    tags: [v*]

jobs:
  build:
    name: Build image
    runs-on: ubuntu-latest
    steps:
      - name: Checkout the repository
        uses: actions/checkout@v2.3.4
      - name: Login to DockerHub
        uses: docker/login-action@v1.10.0
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
      - name: Set add-on version
        run: |
          ADDON_VERSION=$( cut -c12- <<< ${{ github.ref }} )
          sed -i "s/dev/$ADDON_VERSION/g" filiibot/config.json
      - name: Home Assistant builder
        uses: home-assistant/builder@2020.11.0
        with:
          args: |
            --all
            --target filiibot

  publish:
    needs: build
    name: Publish release
    runs-on: ubuntu-latest
    steps:
      - name: Checkout add-on code
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          path: addon
      - name: Checkout repository code
        uses: actions/checkout@v2.3.4
        with:
          persist-credentials: false
          repository: filii-lamberti/repository
          path: repository
      - name: Create local changes and commit files
        continue-on-error: true
        run: |
          ADDON_NAME=$( cut -c22- <<< ${{ github.repository }} )
          ADDON_VERSION=$( cut -c12- <<< ${{ github.ref }} )
          cp -v addon/README.md addon/filiibot/config.json repository/filiibot/
          cd repository
          sed -i "s/dev/$ADDON_VERSION/g" filiibot/config.json
          git config --local user.email "filii.lamberti@gmail.com"
          git config --local user.name "Filii Lamberti"
          git add .
          git commit -m "Publish $ADDON_NAME version $ADDON_VERSION" -a
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          github_token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          directory: repository
          repository: filii-lamberti/repository
